repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  #  - repo: https://github.com/thlorenz/doctoc
  #    rev: v2.1.0
  #    hooks:
  #      - id: doctoc
  #- repo: https://github.com/jackdewinter/pymarkdown
  #  rev: 0.9.2
  #  hooks:
  #    - id: pymarkdown
  #  - repo: https://github.com/pre-commit/mirrors-scss-lint
  #    rev: v0.59.0
  #    hooks:
  #      - id: scss-lint
  #[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat-square)](https://github.com/prettier/prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
          - prettier-plugin-java
#          - prettier-plugin-sh
