language: ruby
dist: focal
rvm:
  - 2.7
install: gem install asciidoctor-pdf --pre
git:
  depth: 1
branches:
  only:
    - main
addons:
  apt:
    packages:
      - zsh
      - mailutils
env:
  global:
    - ENCRYPTION_LABEL: 189e52c2c347
    - COMMIT_AUTHOR_EMAIL: sall@w-ss.io
before_script:
  - sudo apt-get install -y zsh mailutils
  - zsh --version
  - 'zsh -c ''print -rl -- "ZSH_VERSION: $ZSH_VERSION" "ZSH_PATCHLEVEL: $ZSH_PATCHLEVEL"
    "OSTYPE: $OSTYPE" "CPUTYPE: $CPUTYPE" "MACHTYPE: $MACHTYPE"'''
script:
  - git fetch --depth=1 origin tests:tests
  - git worktree add test tests
  - make
  - make -C zsdoc pdf
  - share/deploy_doc.sh
#  - make -C test test VERBOSE=1
#  - make -C test testB VERBOSE=1
#  - make -C test testC VERBOSE=1
#  - make -C test testD VERBOSE=1
#  - make -C test testE VERBOSE=1
notifications:
  email:
    recipients:
      - admin@digitalclouds.dev
    on_success: change
    on_failure: change
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in share/deploy_key.enc -out share/deploy_key -d
