name: Repo Sync

on:
  schedule: 
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch - main
      with:
        source_repo: ss-o/zinit
        source_branch: main
        destination_branch: sync-main
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - uses: repo-sync/pull-request@v2
#      name: Create pull request - main
#      with:
#        source_branch: sync-main
#        destination_branch: main
#        github_token: ${{ secrets.GITHUB_TOKEN }}
